

export default [
    { title: 'Sign Contract', color: '#cfdfff' },
    { title: 'M1 Disburse', color: '#ffdaf6' },
    { title: 'M2 Disburse', color: '#ffdaf6' },
    { title: 'M3 Disburse', color: '#ffdaf6' },
    { title: 'M4 Disburse', color: '#ffdaf6' },
    { title: 'M5 Disburse', color: '#ffdaf6' },
    { title: 'M1', color: '#f99de2' },
    { title: 'M2', color: '#f99de2' },
    { title: 'M3', color: '#f99de2' },
    { title: 'M4', color: '#f99de2' },
    { title: 'M5', color: '#f99de2' },
    { title: 'New', color: '#77d1f3' },
    { title: 'Scope', color: '#d1f7c4' },
    { title: 'Pay Milestone', color: '#c2f5e9' },
    { title: 'Review Milestone', color: '#cfdfff' },
    { title: 'Complete', color: '#cfdfff' },
    { title: 'Closed', color: '#cfdfff' },
    { title: 'Chapter', color: '#ffdaf6' },
    { title: 'Pending Docusign', color: 'rgb(255, 182, 72)' },
    { title: 'Ready for Funding', color: '#5546FF' },
    { title: 'Not Started', color: '#ab48b8' },
    { title: 'Review', color: '#ef6943' },
    { title: 'M1 Review', color: '#f99de2' },
    { title: 'M2 Review', color: '#f99de2' },
    { title: 'M3 Review', color: '#f99de2' },
    { title: 'M4 Review', color: '#f99de2' },
    { title: 'M5 Review', color: '#f99de2' },
    { title: 'In Progress', color: '#f99de2' },
    { title: 'Completed', color: 'black' },
    { title: 'Under Review', color: 'rgb(255, 182, 72)' },
    { title: 'Mark as Followed Up', color: '#5546FF' },
    { title: 'Followed Up', color: '#D3D3D3' },
    { title: 'Issue', color: '#0A0A0A' },
]