
export const ADD_GRANT_REQUEST = 'ADD_GRANT_REQUEST';
export const ADD_GRANT_SUCCESS = 'ADD_GRANT_SUCCESS';
export const ADD_GRANT_FAILED = 'ADD_GRANT_FAILED';

export const APPLY_GRANT_REQUEST = 'APPLY_GRANT_REQUEST';
export const APPLY_GRANT_SUCCESS = 'APPLY_GRANT_SUCCESS';
export const APPLY_GRANT_FAILED = 'APPLY_GRANT_FAILED';

export const APPLY_GRANT_STATUS = 'APPLY_GRANT_STATUS';

export const DELETE_GRANT_REQUEST = 'DELETE_GRANT_REQUEST';
export const DELETE_GRANT_SUCCESS = 'DELETE_GRANT_SUCCESS';
export const DELETE_GRANT_FAILED = 'DELETE_GRANT_FAILED';

export const FETCH_GRANTS_REQUEST = 'FETCH_GRANTS_REQUEST';
export const FETCH_GRANTS_SUCCESS = 'FETCH_GRANTS_SUCCESS';
export const FETCH_GRANTS_FAILED = 'FETCH_GRANTS_FAILED';

export const FETCH_STALE_GRANTS_REQUEST = 'FETCH_STALE_GRANTS_REQUEST';
export const FETCH_STALE_GRANTS_SUCCESS = 'FETCH_STALE_GRANTS_SUCCESS';
export const FETCH_STALE_GRANTS_FAILED = 'FETCH_STALE_GRANTS_FAILED';

export const FETCH_QUEUED_GRANTS_REQUEST = 'FETCH_QUEUED_GRANTS_REQUEST';
export const FETCH_QUEUED_GRANTS_SUCCESS = 'FETCH_QUEUED_GRANTS_SUCCESS';
export const FETCH_QUEUED_GRANTS_FAILED = 'FETCH_QUEUED_GRANTS_FAILED';

export const FETCH_GRANT_BY_ID_REQUEST = 'FETCH_GRANT_BY_ID_REQUEST';
export const FETCH_GRANT_BY_ID_SUCCESS = 'FETCH_GRANT_BY_ID_SUCCESS';
export const FETCH_GRANT_BY_ID_FAILED = 'FETCH_GRANT_BY_ID_FAILED';

export const FETCH_GRANT_REQUEST = 'FETCH_GRANT_REQUEST';
export const FETCH_GRANT_SUCCESS = 'FETCH_GRANT_SUCCESS';
export const FETCH_GRANT_FAILED = 'FETCH_GRANT_FAILED';

export const UPDATE_GRANT_REQUEST = 'UPDATE_GRANT_REQUEST';
export const UPDATE_GRANT_SUCCESS = 'UPDATE_GRANT_SUCCESS';
export const UPDATE_GRANT_FAILED = 'UPDATE_GRANT_FAILED';

export const APPROVE_GRANT_REQUEST = 'APPROVE_GRANT_REQUEST';
export const APPROVE_GRANT_SUCCESS = 'APPROVE_GRANT_SUCCESS';
export const APPROVE_GRANT_FAILED = 'APPROVE_GRANT_FAILED';

export const DENY_GRANT_REQUEST = 'DENY_GRANT_REQUEST';
export const DENY_GRANT_SUCCESS = 'DENY_GRANT_SUCCESS';
export const DENY_GRANT_FAILED = 'DENY_GRANT_FAILED';

export const UPDATE_GRANT_STATUS_REQUEST = 'UPDATE_GRANT_STATUS_REQUEST';
export const UPDATE_GRANT_STATUS_SUCCESS = 'UPDATE_GRANT_STATUS_SUCCESS';
export const UPDATE_GRANT_STATUS_FAILED = 'UPDATE_GRANT_STATUS_FAILED';

export const UPDATE_STALE_GRANT_REQUEST = 'UPDATE_STALE_GRANT_REQUEST';
export const UPDATE_STALE_GRANT_SUCCESS = 'UPDATE_STALE_GRANT_SUCCESS';
export const UPDATE_STALE_GRANT_FAILED = 'UPDATE_STALE_GRANT_FAILED';

export const UPDATE_QUEUED_GRANT_REQUEST = 'UPDATE_QUEUED_GRANT_REQUEST';
export const UPDATE_QUEUED_GRANT_SUCCESS = 'UPDATE_QUEUED_GRANT_SUCCESS';
export const UPDATE_QUEUED_GRANT_FAILED = 'UPDATE_QUEUED_GRANT_FAILED';

export const FETCH_GRANT_BY_TOKEN_REQUEST = 'FETCH_GRANT_BY_TOKEN_REQUEST';
export const FETCH_GRANT_BY_TOKEN_SUCCESS = 'FETCH_GRANT_BY_TOKEN_SUCCESS';
export const FETCH_GRANT_BY_TOKEN_FAILED = 'FETCH_GRANT_BY_TOKEN_FAILED';
