
export const ADD_GRANT_COMMENT_REQUEST = 'ADD_GRANT_COMMENT_REQUEST';
export const ADD_GRANT_COMMENT_SUCCESS = 'ADD_GRANT_COMMENT_SUCCESS';
export const ADD_GRANT_COMMENT_FAILED = 'ADD_GRANT_COMMENT_FAILED';

export const FETCH_GRANT_COMMENTS_REQUEST = 'FETCH_GRANT_COMMENTS_REQUEST';
export const FETCH_GRANT_COMMENTS_SUCCESS = 'FETCH_GRANT_COMMENTS_SUCCESS';
export const FETCH_GRANT_COMMENTS_FAILED = 'FETCH_GRANT_COMMENTS_FAILED';

export const DELETE_GRANT_COMMENT_REQUEST = 'DELETE_GRANT_COMMENT_REQUEST';
export const DELETE_GRANT_COMMENT_SUCCESS = 'DELETE_GRANT_COMMENT_SUCCESS';
export const DELETE_GRANT_COMMENT_FAILED = 'DELETE_GRANT_COMMENT_FAILED';

export const UPDATE_GRANT_COMMENT_REQUEST = 'UPDATE_GRANT_COMMENT_REQUEST';
export const UPDATE_GRANT_COMMENT_SUCCESS = 'UPDATE_GRANT_COMMENT_SUCCESS';
export const UPDATE_GRANT_COMMENT_FAILED = 'UPDATE_GRANT_COMMENT_FAILED';
