
export const ADD_MILESTONE_REQUEST = 'ADD_MILESTONE_REQUEST';
export const ADD_MILESTONE_SUCCESS = 'ADD_MILESTONE_SUCCESS';
export const ADD_MILESTONE_FAILED = 'ADD_MILESTONE_FAILED';

export const DELETE_MILESTONE_REQUEST = 'DELETE_MILESTONE_REQUEST';
export const DELETE_MILESTONE_SUCCESS = 'DELETE_MILESTONE_SUCCESS';
export const DELETE_MILESTONE_FAILED = 'DELETE_MILESTONE_FAILED';

export const FETCH_MILESTONES_REQUEST = 'FETCH_MILESTONES_REQUEST';
export const FETCH_MILESTONES_SUCCESS = 'FETCH_MILESTONES_SUCCESS';
export const FETCH_MILESTONES_FAILED = 'FETCH_MILESTONES_FAILED';

export const FETCH_MILESTONE_BY_ID_REQUEST = 'FETCH_MILESTONE_BY_ID_REQUEST';
export const FETCH_MILESTONE_BY_ID_SUCCESS = 'FETCH_MILESTONE_BY_ID_SUCCESS';
export const FETCH_MILESTONE_BY_ID_FAILED = 'FETCH_MILESTONE_BY_ID_FAILED';

export const FETCH_MILESTONE_REQUEST = 'FETCH_MILESTONE_REQUEST';
export const FETCH_MILESTONE_SUCCESS = 'FETCH_MILESTONE_SUCCESS';
export const FETCH_MILESTONE_FAILED = 'FETCH_MILESTONE_FAILED';

export const UPDATE_MILESTONE_REQUEST = 'UPDATE_MILESTONE_REQUEST';
export const UPDATE_MILESTONE_SUCCESS = 'UPDATE_MILESTONE_SUCCESS';
export const UPDATE_MILESTONE_FAILED = 'UPDATE_MILESTONE_FAILED';

export const UPDATE_MILESTONE_DATA_REQUEST = 'UPDATE_MILESTONE_DATA_REQUEST';
export const UPDATE_MILESTONE_DATA_SUCCESS = 'UPDATE_MILESTONE_DATA_SUCCESS';
export const UPDATE_MILESTONE_DATA_FAILED = 'UPDATE_MILESTONE_DATA_FAILED';
