
export const ADD_RECIPIENT_REQUEST = 'ADD_RECIPIENT_REQUEST';
export const ADD_RECIPIENT_SUCCESS = 'ADD_RECIPIENT_SUCCESS';
export const ADD_RECIPIENT_FAILED = 'ADD_RECIPIENT_FAILED';

export const DELETE_RECIPIENT_REQUEST = 'DELETE_RECIPIENT_REQUEST';
export const DELETE_RECIPIENT_SUCCESS = 'DELETE_RECIPIENT_SUCCESS';
export const DELETE_RECIPIENT_FAILED = 'DELETE_RECIPIENT_FAILED';

export const FETCH_RECIPIENTS_REQUEST = 'FETCH_RECIPIENTS_REQUEST';
export const FETCH_RECIPIENTS_SUCCESS = 'FETCH_RECIPIENTS_SUCCESS';
export const FETCH_RECIPIENTS_FAILED = 'FETCH_RECIPIENTS_FAILED';

export const FETCH_RECIPIENT_BY_ID_REQUEST = 'FETCH_RECIPIENT_BY_ID_REQUEST';
export const FETCH_RECIPIENT_BY_ID_SUCCESS = 'FETCH_RECIPIENT_BY_ID_SUCCESS';
export const FETCH_RECIPIENT_BY_ID_FAILED = 'FETCH_RECIPIENT_BY_ID_FAILED';

export const FETCH_RECIPIENT_REQUEST = 'FETCH_RECIPIENT_REQUEST';
export const FETCH_RECIPIENT_SUCCESS = 'FETCH_RECIPIENT_SUCCESS';
export const FETCH_RECIPIENT_FAILED = 'FETCH_RECIPIENT_FAILED';

export const UPDATE_RECIPIENT_REQUEST = 'UPDATE_RECIPIENT_REQUEST';
export const UPDATE_RECIPIENT_SUCCESS = 'UPDATE_RECIPIENT_SUCCESS';
export const UPDATE_RECIPIENT_FAILED = 'UPDATE_RECIPIENT_FAILED';
