
export const ADD_USERNOTE_REQUEST = 'ADD_USERNOTE_REQUEST';
export const ADD_USERNOTE_SUCCESS = 'ADD_USERNOTE_SUCCESS';
export const ADD_USERNOTE_FAILED = 'ADD_USERNOTE_FAILED';

export const DELETE_USERNOTE_REQUEST = 'DELETE_USERNOTE_REQUEST';
export const DELETE_USERNOTE_SUCCESS = 'DELETE_USERNOTE_SUCCESS';
export const DELETE_USERNOTE_FAILED = 'DELETE_USERNOTE_FAILED';

export const FETCH_USERNOTES_REQUEST = 'FETCH_USERNOTES_REQUEST';
export const FETCH_USERNOTES_SUCCESS = 'FETCH_USERNOTES_SUCCESS';
export const FETCH_USERNOTES_FAILED = 'FETCH_USERNOTES_FAILED';

export const FETCH_USERNOTE_BY_ID_REQUEST = 'FETCH_USERNOTE_BY_ID_REQUEST';
export const FETCH_USERNOTE_BY_ID_SUCCESS = 'FETCH_USERNOTE_BY_ID_SUCCESS';
export const FETCH_USERNOTE_BY_ID_FAILED = 'FETCH_USERNOTE_BY_ID_FAILED';

export const FETCH_USERNOTE_REQUEST = 'FETCH_USERNOTE_REQUEST';
export const FETCH_USERNOTE_SUCCESS = 'FETCH_USERNOTE_SUCCESS';
export const FETCH_USERNOTE_FAILED = 'FETCH_USERNOTE_FAILED';

export const UPDATE_USERNOTE_REQUEST = 'UPDATE_USERNOTE_REQUEST';
export const UPDATE_USERNOTE_SUCCESS = 'UPDATE_USERNOTE_SUCCESS';
export const UPDATE_USERNOTE_FAILED = 'UPDATE_USERNOTE_FAILED';
